import type { Metadata } from 'next';
import AppHeader from '@/components/AppHeader';
import AppFooter from '@/components/AppFooter';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Read the Mealio Terms of Service to understand the rules and guidelines for using our app.',
};

export default function TermsPage() {
  const effective = 'February 22, 2026';

  return (
    <div style={{ minHeight: '100vh', background: '#f5f5f5', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif' }}>
      <AppHeader />

      <div style={{ maxWidth: '800px', margin: '0 auto', padding: '40px 24px', lineHeight: 1.75, color: '#333', fontSize: '15px' }}>
        <div style={{ marginBottom: '32px' }}>
          <p style={{ margin: '0 0 4px', fontSize: '13px', color: '#888' }}>Legal</p>
          <h1 style={{ margin: '0 0 6px', fontSize: '26px', fontWeight: 700, color: '#111' }}>Terms and Conditions</h1>
          <p style={{ margin: 0, fontSize: '13px', color: '#888' }}>Effective date: {effective}</p>
        </div>

        <p>
          Please read these Terms and Conditions ("Terms") carefully before using the Mealio platform, including the Mealio browser extension, website located at mealio.co, and any related services (collectively, the "Service") operated by Mealio ("we," "us," or "our").
        </p>
        <p>
          By accessing or using the Service, you agree to be bound by these Terms. If you do not agree to any part of these Terms, you may not use the Service.
        </p>

        <hr style={{ border: 'none', borderTop: '1px solid #e0e0e0', margin: '32px 0' }} />

        {/* 1 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginBottom: '12px' }}>1. Description of Service</h2>
        <p>
          Mealio is a grocery automation platform that allows users to save meal recipes and automatically add associated ingredients to online grocery store shopping carts. The Service operates as a browser extension and accompanying web application.
        </p>

        {/* 2 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>2. Eligibility and Account Registration</h2>
        <p>
          You must be at least 13 years of age to use the Service. By creating an account, you represent that all information you provide is accurate and complete. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately at contact@mealio.co if you suspect unauthorized access to your account.
        </p>
        <p>
          We reserve the right to suspend or terminate accounts that violate these Terms or that we reasonably believe have been compromised.
        </p>

        {/* 3 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>3. Subscriptions and Payment</h2>
        <p>
          Mealio offers a free tier with limited features and a paid subscription plan ("Full Access") that unlocks additional functionality. Subscription fees are billed on a monthly or annual basis, as selected at the time of purchase. All fees are stated in US dollars and are non-refundable except where required by applicable law.
        </p>
        <p>
          We reserve the right to modify subscription pricing at any time. We will provide at least 30 days' advance notice of any price changes. Continued use of the Service after a price change constitutes acceptance of the new pricing.
        </p>
        <p>
          You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of the current billing cycle. We do not prorate partial billing periods.
        </p>

        {/* 4 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>4. Creator Partner Program</h2>
        <p>
          Mealio operates a Creator Partner Program ("Creator Program") that allows approved food creators to publish meal recipes to the Mealio Discover feed, accessible by all users of the Service. Participation in the Creator Program is subject to application, review, and approval at our sole discretion.
        </p>

        <h3 style={{ fontSize: '15px', fontWeight: 700, color: '#333', marginTop: '20px', marginBottom: '8px' }}>4.1 Profit Share</h3>
        <p>
          Approved Creator Partners are eligible to receive a share of quarterly subscription profit generated by the Service. Profit share is calculated based on each creator's proportion of total platform meal saves during the applicable period, as described in the Creator Portal. Profit share payouts are issued quarterly for amounts exceeding $25 USD. We reserve the right to modify the profit share formula, payout threshold, or payout schedule upon 30 days' written notice to active Creator Partners.
        </p>

        <h3 style={{ fontSize: '15px', fontWeight: 700, color: '#333', marginTop: '20px', marginBottom: '8px' }}>4.2 Content Standards</h3>
        <p>
          Creator Partners agree to publish only original recipes and meal content for which they hold the necessary rights. Content must not infringe on any third-party intellectual property rights, contain false or misleading information, or violate any applicable law. We reserve the right to remove any content that violates these standards without prior notice.
        </p>

        <h3 style={{ fontSize: '15px', fontWeight: 700, color: '#333', marginTop: '20px', marginBottom: '8px' }}>4.3 Exclusivity and Non-Compete Obligation</h3>
        <p>
          By participating in the Creator Program, Creator Partners agree that, during the term of their participation, they will not enter into a partnership, sponsorship, affiliate arrangement, or any formal content-creation relationship with any application, platform, or service that substantially replicates or directly competes with the core functionality of Mealio — specifically, the automated addition of recipe-based grocery ingredients to online shopping carts ("Competing Service").
        </p>
        <p>
          This restriction does not prohibit Creator Partners from: (a) posting recipe content on general-purpose social media platforms (e.g., Instagram, TikTok, YouTube); (b) maintaining a personal food blog or website; (c) participating in unrelated brand sponsorships or partnerships; or (d) using any grocery store's own native application or website.
        </p>
        <p>
          If a Creator Partner is uncertain whether a particular arrangement constitutes a Competing Service relationship, they are encouraged to seek clarification by contacting us at contact@mealio.co prior to entering into that arrangement. Violation of this provision may result in immediate termination from the Creator Program and forfeiture of any unpaid profit share amounts.
        </p>

        <h3 style={{ fontSize: '15px', fontWeight: 700, color: '#333', marginTop: '20px', marginBottom: '8px' }}>4.4 License Grant</h3>
        <p>
          By submitting content to the Creator Program, you grant Mealio a non-exclusive, royalty-free, worldwide license to display, reproduce, and distribute your submitted meal content within the Service for the purpose of operating the Creator Program. You retain ownership of your original content. This license terminates when your content is removed from the Service or your Creator Partner status is terminated, except that we may retain cached or archived copies as required by our standard data retention practices.
        </p>

        <h3 style={{ fontSize: '15px', fontWeight: 700, color: '#333', marginTop: '20px', marginBottom: '8px' }}>4.5 Termination from Creator Program</h3>
        <p>
          Either party may terminate Creator Partner status at any time with written notice to the other party. Upon termination, your published meals will be removed from the Discover feed within a reasonable time period. Any accrued but unpaid profit share amounts will be paid at the next regular payout date, provided the minimum payout threshold is met, unless termination is due to a violation of these Terms, in which case unpaid amounts may be forfeited.
        </p>

        {/* 5 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>5. Intellectual Property</h2>
        <p>
          The Mealio name, logo, extension, website design, and all software comprising the Service are the exclusive property of Mealio and are protected by applicable intellectual property laws. You may not copy, modify, distribute, or create derivative works of any part of the Service without our express written permission.
        </p>
        <p>
          You retain ownership of any personal meal data, recipes, and content you create within the Service. By using the Service, you grant us a limited license to store and process your content solely for the purpose of providing the Service to you.
        </p>

        {/* 6 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>6. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul style={{ paddingLeft: '24px', marginTop: '8px' }}>
          <li style={{ marginBottom: '6px' }}>Use the Service for any unlawful purpose or in violation of any applicable regulation;</li>
          <li style={{ marginBottom: '6px' }}>Attempt to gain unauthorized access to any part of the Service or its underlying infrastructure;</li>
          <li style={{ marginBottom: '6px' }}>Reverse engineer, decompile, or disassemble any component of the Service;</li>
          <li style={{ marginBottom: '6px' }}>Use automated tools to scrape, crawl, or harvest data from the Service;</li>
          <li style={{ marginBottom: '6px' }}>Interfere with or disrupt the integrity or performance of the Service;</li>
          <li style={{ marginBottom: '6px' }}>Impersonate any person or entity or misrepresent your affiliation with any person or entity.</li>
        </ul>

        {/* 7 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>7. Third-Party Services</h2>
        <p>
          The Service integrates with third-party grocery platforms (including but not limited to HEB, Walmart, and Kroger) to automate cart operations. These integrations rely on the publicly accessible interfaces of those platforms. We make no representations regarding the availability, accuracy, or reliability of any third-party platform. Changes to third-party platforms may affect Service functionality, and we are not responsible for any interruptions resulting from such changes.
        </p>

        {/* 8 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>8. Privacy</h2>
        <p>
          Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the Service, you consent to our collection and use of information as described in the Privacy Policy. For questions about data practices, contact us at contact@mealio.co.
        </p>

        {/* 9 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>9. Disclaimers</h2>
        <p>
          THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
        </p>
        <p>
          We do not guarantee that any particular grocery item will be found, added to a cart, or available at any store. Product availability, pricing, and search results are determined solely by the relevant grocery platform.
        </p>

        {/* 10 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>10. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, MEALIO SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>
        <p>
          IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATED TO THESE TERMS OR THE SERVICE EXCEED THE GREATER OF (A) THE TOTAL FEES YOU PAID TO US IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED US DOLLARS ($100).
        </p>

        {/* 11 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>11. Indemnification</h2>
        <p>
          You agree to indemnify, defend, and hold harmless Mealio and its officers, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising out of or in any way connected with your use of the Service, your violation of these Terms, or your infringement of any third-party rights.
        </p>

        {/* 12 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>12. Termination</h2>
        <p>
          We may suspend or terminate your access to the Service at any time, with or without cause, and with or without notice. Upon termination, your right to use the Service ceases immediately. Provisions of these Terms that by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, indemnification, and limitations of liability.
        </p>

        {/* 13 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>13. Governing Law and Dispute Resolution</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the State of Texas, without regard to its conflict of law provisions. Any dispute arising from or relating to these Terms or the Service shall be resolved exclusively in the state or federal courts located in Texas, and you consent to personal jurisdiction in those courts.
        </p>

        {/* 14 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>14. Changes to These Terms</h2>
        <p>
          We reserve the right to update these Terms at any time. We will notify you of material changes by posting the updated Terms on this page with a new effective date and, where appropriate, by sending an email to the address associated with your account. Your continued use of the Service after any changes constitutes your acceptance of the revised Terms.
        </p>

        {/* 15 */}
        <h2 style={{ fontSize: '18px', fontWeight: 700, color: '#222', marginTop: '32px', marginBottom: '12px' }}>15. Contact</h2>
        <p>
          If you have any questions about these Terms, please contact us at:
        </p>
        <p style={{ marginTop: '8px' }}>
          <strong>Mealio</strong><br />
          <a href="mailto:contact@mealio.co" style={{ color: '#dd0031' }}>contact@mealio.co</a>
        </p>

      </div>
      <AppFooter />
    </div>
  );
}
