-- Q1 automation reliability work: remote store config + a per-step telemetry funnel.
--
-- Two independent features, one migration because they ship together:
--
--   1. automation_config — versioned JSON config for the mobile WebView cart
--      engine (selectors, URLs, timeouts, worker counts, feature flags). The app
--      fetches the ACTIVE row at launch and merges it over its bundled defaults,
--      so a store renaming a button becomes a config push instead of an App Store
--      release. Exactly one row may be active at a time.
--
--   2. automation_steps — one row per step of an add-to-cart run (login check,
--      search, candidates, add click, confirm signal, reconcile). Lets us answer
--      "what percent of HEB adds confirmed on the first click this week" without
--      asking a user for their logs, and alert when a store's confirm rate drops.
--
-- Additive and backward-compatible: existing automation_runs rows keep NULL in
-- the new columns, and the app works unchanged if these tables are empty (it
-- falls back to its bundled config and simply drops step reports).
--
-- Run this in the Supabase SQL editor BEFORE deploying the code that uses it.

-- ── 1. Remote automation config ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS automation_config (
  id          uuid NOT NULL DEFAULT gen_random_uuid(),
  -- Monotonic version the client reports back in telemetry, so a bad config is
  -- attributable: a confirm-rate drop can be traced to the version that caused it.
  version     int NOT NULL,
  -- Partial config: only the keys that OVERRIDE the app's bundled defaults.
  -- Never a full snapshot, so an old client ignoring an unknown key still works.
  config      jsonb NOT NULL,
  is_active   boolean NOT NULL DEFAULT false,
  notes       text,
  created_by  uuid,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS automation_config_version_key
  ON automation_config (version);

-- At most one active config. A partial unique index on a constant expression is
-- the standard way to enforce "only one row where is_active" in Postgres.
CREATE UNIQUE INDEX IF NOT EXISTS automation_config_single_active_key
  ON automation_config ((is_active)) WHERE is_active;

-- Postgres has no ADD CONSTRAINT IF NOT EXISTS, so guard each one to keep the
-- whole migration safely re-runnable (it is applied by hand in the SQL editor).
DO $$ BEGIN
  ALTER TABLE automation_config
    ADD CONSTRAINT automation_config_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES user_profiles (id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── 2. Per-step telemetry funnel ────────────────────────────────────────────

-- Attribute each run to the client and config that produced it, so a regression
-- can be traced to an app release or a config push.
ALTER TABLE automation_runs
  ADD COLUMN IF NOT EXISTS config_version int,
  ADD COLUMN IF NOT EXISTS app_version    text,
  ADD COLUMN IF NOT EXISTS platform       text;

CREATE TABLE IF NOT EXISTS automation_steps (
  id             bigint GENERATED BY DEFAULT AS IDENTITY,
  run_id         uuid NOT NULL,
  user_id        uuid NOT NULL,
  -- Denormalized from the run so per-store funnel queries never need the join.
  store_id       text NOT NULL,
  -- 'login_check' | 'search' | 'candidates' | 'add_click' | 'confirm' |
  -- 'reconcile' | 'blocked' | 'run_summary' (see AUTOMATION_STEPS in the app).
  step           text NOT NULL,
  -- 'ok' | 'empty' | 'timeout' | 'error' | 'blocked' | 'skipped'
  outcome        text NOT NULL,
  -- Client-assigned monotonic sequence within the run. Preserves ordering even
  -- though steps upload in batches and rows share an occurred_at millisecond.
  seq            int NOT NULL,
  duration_ms    int,
  -- Which ingredient index this step belongs to; NULL for run-level steps.
  item_index     int,
  -- Small structured payload: candidate count, confirm strategy, retry number,
  -- failure reason. Deliberately capped client-side — never raw page HTML.
  detail         jsonb,
  config_version int,
  app_version    text,
  platform       text,
  occurred_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

-- Idempotent ingest: the client retries a failed batch, and at-least-once
-- delivery would otherwise double-count. (run_id, seq) is unique per step.
CREATE UNIQUE INDEX IF NOT EXISTS automation_steps_run_seq_key
  ON automation_steps (run_id, seq);

-- The funnel dashboard's main query: per store, per step, over a time window.
CREATE INDEX IF NOT EXISTS idx_automation_steps_store_step_time
  ON automation_steps (store_id, step, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_automation_steps_run
  ON automation_steps (run_id);

-- ON DELETE CASCADE on both: a deleted account or a pruned run must take its
-- step rows with it, otherwise the funnel keeps counting orphans forever.
DO $$ BEGIN
  ALTER TABLE automation_steps
    ADD CONSTRAINT automation_steps_run_id_fkey
    FOREIGN KEY (run_id) REFERENCES automation_runs (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE automation_steps
    ADD CONSTRAINT automation_steps_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES user_profiles (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── 3. Seed an empty active config ──────────────────────────────────────────
-- Version 1 overrides nothing, so every client keeps using its bundled defaults
-- until an admin actually publishes a change. This makes the GET endpoint return
-- 200 with a real version from day one rather than a special-cased 404.
INSERT INTO automation_config (version, config, is_active, notes)
  SELECT 1, '{}'::jsonb, true, 'Bootstrap: no overrides, clients use bundled defaults.'
  WHERE NOT EXISTS (SELECT 1 FROM automation_config);
