-- MEAL-222. Every recipe import, with the tokens and the cost it actually spent.
--
-- Nothing new is measured here. `lib/import/anthropic.ts` already reads
-- `usage.input_tokens` and `usage.output_tokens` off every response, records the
-- CONCRETE model snapshot the API served (claude-haiku-4-5-20251001, not the
-- alias we sent), and prices it -- per call, gate and extraction separately.
-- Then `ImportTelemetry` flattened the lot to one `costUsd` and wrote a log
-- line. This is the promotion that comment asked for: "it can be promoted to a
-- table once the poller makes the volume worth querying", and opening imports to
-- users (MEAL-221) is that moment.
--
-- ONE ROW PER ATTEMPT, NOT PER SUCCESS. A rejection costs money too -- about
-- $0.0031 when the gate says no -- and an import that failed AFTER paying for
-- extraction is exactly the row worth finding. Filtering to successes would hide
-- the spend that has nothing to show for it.
--
-- TOKENS AND COST, PER STAGE. Both, and separately, for three reasons:
--
--   * Prices change and models change. Tokens are the FACT and the dollar figure
--     is a derivation, so keeping both means a repricing can be recomputed over
--     history rather than leaving a column that quietly means something
--     different before and after a date.
--   * "How often does the gate reject, and what does rejecting cost" cannot be
--     answered from a single total.
--   * TYPICAL_IMPORT_TOKENS in lib/import/cost.ts was measured in MEAL-71 when
--     extraction ran on Opus with adaptive thinking. Extraction is Haiku now and
--     thinking is off, and nobody has re-measured the SHAPE. Pricing follows the
--     model automatically; the token counts do not. A week of these rows
--     replaces that estimate with fact.
--
-- WHY ONE TABLE AND NOT TWO. `actor` distinguishes an import a creator ran from
-- one a user ran, which is the split Stephen asked for. Two tables would make
-- every "what did imports cost this month" query a UNION, and MEAL-221's
-- per-user budget needs a count that cannot be allowed to disagree with the
-- accounting -- which it will, if they are two different counters.

CREATE TABLE IF NOT EXISTS public.recipe_imports (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at  timestamptz NOT NULL DEFAULT now(),

  -- ── who ───────────────────────────────────────────────────────────────────
  -- Nullable: the poller imports on a creator's behalf with no user in the
  -- request, and a row with no user is still a row worth costing.
  user_id      uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  creator_id   uuid REFERENCES public.creators(id) ON DELETE SET NULL,
  -- 'creator' | 'user'. Unconstrained text on purpose, like `phase` in
  -- MEAL-219: a newer server shipping a third kind of actor must not have its
  -- rows REJECTED by an older database, which loses exactly the rows we most
  -- want to see at the moment something new is happening.
  actor        text NOT NULL,

  -- ── what ──────────────────────────────────────────────────────────────────
  -- THE URL IS STORED, NOT HASHED, and that was a real choice. It is the
  -- creator's own published page, already public, and already written in full
  -- to creator_source_items and to the log line this replaces -- so hashing
  -- here would protect nothing while making the two questions this table exists
  -- for unanswerable: "which import cost this much" and "what does a KEPT meal
  -- cost", the second of which needs a join to the draft the URL produced.
  -- Capped so a pathological URL cannot bloat the row.
  url          text,
  platform     text,
  path         text,

  -- ── outcome ───────────────────────────────────────────────────────────────
  outcome      text NOT NULL,
  stage        text NOT NULL,
  reason       text,
  gate_verdict text,
  gate_source  text,
  -- A cache hit costs nothing and must not be averaged in with calls that paid.
  cached       boolean NOT NULL DEFAULT false,

  -- ── tokens and cost, per stage ────────────────────────────────────────────
  gate_model            text,
  gate_input_tokens     integer,
  gate_output_tokens    integer,
  gate_cost_usd         numeric(10, 6),
  extract_model         text,
  extract_input_tokens  integer,
  extract_output_tokens integer,
  extract_cost_usd      numeric(10, 6),
  -- Stored rather than generated. It is the sum of the two above TODAY, but a
  -- third paid stage would make a generated column silently wrong at exactly
  -- the moment it mattered, and this is the number every dashboard reads.
  total_cost_usd        numeric(10, 6) NOT NULL DEFAULT 0,

  -- ── quality ───────────────────────────────────────────────────────────────
  ingredient_count integer,
  confidence_green integer,
  confidence_amber integer,
  confidence_red   integer,

  duration_ms integer,

  -- Long enough for any real URL, short enough that a crafted one cannot bloat
  -- the table. Enforced here rather than only in the writer, because the writer
  -- is not the only thing that will ever insert.
  CONSTRAINT recipe_imports_url_len CHECK (url IS NULL OR length(url) <= 2048)
);

COMMENT ON TABLE public.recipe_imports IS
  'MEAL-222. One row per import ATTEMPT, creator or user, with per-stage tokens and cost. Rejections included: they cost money too.';
COMMENT ON COLUMN public.recipe_imports.actor IS
  'MEAL-222. creator|user. Unconstrained on purpose so a newer server is never rejected by an older database.';
COMMENT ON COLUMN public.recipe_imports.gate_model IS
  'MEAL-222. The CONCRETE model snapshot the API served, not the alias we sent. The client goes to the trouble of capturing it and that is worthless unless it is persisted.';
COMMENT ON COLUMN public.recipe_imports.total_cost_usd IS
  'MEAL-222. Sum of the per-stage costs. Stored, not generated: a third paid stage would make a generated column silently wrong.';

-- ── indexes: the three questions this table exists to answer ────────────────

-- "What did imports cost this month, split by creator vs user."
CREATE INDEX IF NOT EXISTS idx_recipe_imports_actor_time
  ON public.recipe_imports (actor, occurred_at DESC);

-- MEAL-221's per-user monthly budget. Partial, because a row with no user is
-- never part of anyone's allowance and carrying it here only slows the count.
CREATE INDEX IF NOT EXISTS idx_recipe_imports_user_time
  ON public.recipe_imports (user_id, occurred_at DESC)
  WHERE user_id IS NOT NULL;

-- "How often does the gate reject, and what does rejecting cost."
CREATE INDEX IF NOT EXISTS idx_recipe_imports_outcome_time
  ON public.recipe_imports (outcome, stage, occurred_at DESC);

-- ── RLS, on from birth ──────────────────────────────────────────────────────
--
-- This table is for the server. It carries what every creator publishes, what
-- it cost us, and a URL per row, none of which belongs to the anon key that
-- ships inside mealio.co's JavaScript bundle.
--
-- No policies are added, which with RLS enabled means anon and authenticated
-- can do nothing at all. `service_role` bypasses RLS, so the writer and the
-- admin read are unaffected. This is the standing rule from the RLS lockdown:
-- a new table is never born open.

ALTER TABLE public.recipe_imports ENABLE ROW LEVEL SECURITY;

-- ── retention ───────────────────────────────────────────────────────────────
--
-- Decided here rather than left to be decided later, which is what MEAL-219's
-- rollup ticket asked for. KEPT OUTRIGHT, no prune: this is one row per import,
-- not one per step. At a hundred imports a month it is 1,200 rows a year, and
-- the whole point of "cost per KEPT meal" is a question asked over history. A
-- prune here would delete the answer to the question the table was built for.
